# Generated by Django 5.0.2 on 2024-07-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='openai_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oura_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='coliver_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('ru', 'Russian'), ('ko', 'Korean')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='travel_status',
            field=models.CharField(blank=True, choices=[('ready_to_travel', 'Ready to travel'), ('not_ready_to_travel', 'Not ready to travel'), ('will_be_soon', 'Will be soon')], max_length=255, null=True),
        ),
    ]
