# Generated by Django 5.0.2 on 2024-08-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
