# Generated by Django 5.0.2 on 2024-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_user_is_email_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
