# Generated by Django 5.0.2 on 2024-07-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_remove_trip_is_flexible_alter_trip_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('RUB', 'RUB'), ('KZT', 'KZT')], max_length=255, null=True),
        ),
    ]
